version: '3.4'

services:
  sampleproject:
    image: authly-web-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
